version: "3.8"
services:
  db:
    image: postgres:16
    container_name: legendscombat-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: legendscombat
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}
