server:
    port: 8080

spring:
    application:
        name: LegendsCombat
    datasource:
        url: ${DB_URL:jdbc:postgresql://localhost:5432/legendscombat}
        username: ${DB_USERNAME:postgres}
        password: ${DB_PASSWORD:postgres}
    liquibase:
        change-log: classpath:db/changelog/db.changelog-master.yaml
    jpa:
        hibernate:
            ddl-auto: validate
        properties:
            hibernate:
                format_sql: true
                dialect: org.hibernate.dialect.PostgreSQLDialect
        open-in-view: false
    thymeleaf:
        cache: false


logging:
    level:
        org.springframework.security: INFO